version: "3.6"
services:
  pg_db:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    network_mode: host
#  nginx:
#    image: nginx:1.17.2-alpine
#    container_name: nginx
#    volumes:
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
##      - ./dist:/var/www/html
#    ports:
#      - "80:80"
#      - "443:443"
#  back-api:
#    build:
#      context: ./
#      dockerfile: docker/api.Dockerfile
#    depends_on:
#        - pg_db
#    container_name: back-api
#    ports:
#      - "8080:8080"
#    network_mode: host
