  version: "3.8"
  services:
    pg_db:
      image: postgres:13.1
      restart: always
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
#      volumes:
#        - ./:/var/lib/postgresql/data
      ports:
        - ${POSTGRES_PORT:-5432}:5432
    webserver:
      build:
        context: docker
        dockerfile: api.Dockerfile
      container_name: back-api
      ports:
        - "8080:8080"
