  version: "3.6"
  services:
    pg_db:
      image: postgres:13.1
      restart: always
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
#      volumes:
#        - ./:/var/lib/postgresql/data
      ports:
        - ${POSTGRES_PORT:-5432}:5432
    webserver:
      env_file:
        - .env
      image: nginx:alpine
      container_name: webserver
      restart: unless-stopped

      ports:
        - "80:80"
        - "443:443"
#      volumes:
#        - ./:/var/www
#        - ./nginx/conf.d/:/etc/nginx/conf.d/