  version: "3.8"
  services:
    pg_db:
      image: postgres:13.1
      restart: always
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      ports:
        - "5432:5432"
#    back-api:
#      build:
#        context: docker
#        dockerfile: api.Dockerfile
#      depends_on:
#        - pg_db
#      container_name: back-api
#      ports:
#        - "8080:8080"
    nginx:
      image: nginx:1.17.2-alpine
#      build:
#        context: docker
#        dockerfile: nginx.Dockerfile
      container_name: nginx
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "80:80"
        - "443:443"
