version: "3.6"
services:
#  pg_db:
#    image: postgres:12.6
##    restart: always
#    environment:
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_DB=${POSTGRES_DB}
#    volumes:
#      - ./pgdata:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    network_mode: host
#  nginx:
#    image: nginx:1.17.2-alpine
#    container_name: nginx
#    volumes:
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
##      - ./dist:/var/www/html
#    ports:
#      - "80:80"
#      - "443:443"
  back-api:
    image: golang
    volumes:
    - .:/back
    working_dir: /back
    env_file:
      - main.env
    command: go run main.go
#    ports:
#      - "8080:8080"
    network_mode: host
#  prediction:
#    build:
#      context: ./
#      dockerfile: docker/py.Dockerfile
#    depends_on:
#      - pg_db
#    container_name: prediction
#    network_mode: host
