database:
  user: andrey
  password: 167839
  net: tcp
  addr: database2.cwu4v7dr4m4k.eu-west-2.rds.amazonaws.com:5432
  dbname: back_db
  allowNativePasswords: true
  params:
    parseTime: "true"

server:
  address: 8080